files.extend-exclude = ["docs/pytket-docs-theming/**"]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
qiskit_aer = "qiskit_aer"
aer = "aer"
anc = "anc"
