files.extend-exclude = ["docs/pytket-docs-theming/**"]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
aer = "aer"
anc = "anc"
arange = "arange"
aer_unitary_b = "aer_unitary_b"
aer_b = "aer_b"
noisy_aer_b = "noisy_aer_b"
