files.extend-exclude = ["docs/pytket-docs-theming/**"]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
aer = "aer"
qiskit_aer = "qiskit_aer"
anc = "anc"
arange = "arange"
aer_unitary_b = "aer_unitary_b"
aer_b = "aer_b"
noisy_aer_b = "noisy_aer_b"
Braket = "Braket"
braket = "braket"
AAS = "AAS"
Strat = "Strat"
strat = "strat"
