#!/bin/sh

python -m pip install -r requirements.txt

python -m pip install --pre git+git://github.com/willsimmons1465/jupyter-sphinx.git@issue-140#egg=jupyter-sphinx

cd manual/
rm -rf build/
sphinx-build -b html . build
cd ..

rm -rf docs/build/html/manual/
cp -r manual/build/ docs/build/html/manual
