#!/bin/sh

python -m pip install -r manual_requirements.txt
python -m pip install -c manual_constraints.txt sphinx sphinx-book-theme sphinx-copybutton jupyter-sphinx quimb
python -m pip install qiskit-algorithms
python -m pip install ipykernel
python -m pip install kahypar

cd manual/

ESCAPED_REQS=$(awk '{printf "%s%s",sep,$0; sep="\\\n"} END{print ""}' ../manual_requirements.txt)
sed "s/REQUIREMENTS/$ESCAPED_REQS/" index-rst-template > index.rst

rm -rf build/
sphinx-build -b html . build -W

rm index.rst
