#!/bin/sh

# if version are updated, update the version in the requirements file 
# and the check-examples.yml, too.
# this duplication is currently necessary because of an issue with the pyjwt
# version required from qcs-api-client < 0.21.0
python -m pip install pytket==1.4.3
python -m pip install pytket-pyquil==0.25.0
python -m pip install qcs-api-client==0.21.0
python -m pip install pytket-cirq==0.25.0
python -m pip install pytket-projectq==0.23.0
python -m pip install pytket-qiskit==0.27.0
python -m pip install pytket-qsharp==0.27.0
python -m pip install pytket-quantinuum==0.6.0
python -m pip install pytket-qulacs==0.21.0

python -m pip install sphinx sphinx-rtd-theme jupyter-sphinx

cd manual/

ESCAPED_REQS=$(awk '{printf "%s%s",sep,$0; sep="\\\n"} END{print ""}' ../requirements.txt)
sed "s/REQUIREMENTS/$ESCAPED_REQS/" index-rst-template > index.rst

rm -rf build/
sphinx-build -b html . build

rm index.rst

cd ..

rm -rf docs/manual/
cp -r manual/build/ docs/manual
