[tool.poetry]
name = "pytket-docs"
package-mode = false
version = "0.1.0"
description = ""
authors = ["CalMacCQ <93673602+CalMacCQ@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytket = { extras = ["zx"], version = "^1.34.0" }
pytket-qiskit = "^0.58.0"
pytket-cirq = "^0.38.0"
pytket-qujax = "0.21.0"
pytest = "^8.3.3"
qiskit-algorithms = "^0.3.1"
ipykernel = "^6.29.4"
kahypar = "^1.3.5"
sphinx-copybutton = "^0.5.2"
quimb = "^1.8.1"
openfermion = "^1.6.1"
ipyparallel = "^8.8.0"
furo = "^2024.8.6"
myst-nb = "^1.1.2"
sphinx-autodoc-typehints = "^2.4.4"
enum-tools = {extras = ["sphinx"], version = "^0.12.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
