#!/usr/bin/env python

import docker

dock = docker.from_env()

dock.containers.run(
    image="rigetti/qvm", command="-S", detach=True, ports={5000: 5000}, remove=True
)
dock.containers.run(
    image="rigetti/quilc", command="-S", detach=True, ports={5555: 5555}, remove=True
)
