#!/usr/bin/env python

import os
from qiskit import IBMQ

if not IBMQ.stored_account():
    token = os.getenv("PYTKET_QA_QISKIT_TOKEN")
    if token:
        IBMQ.save_account(token)

IBMQ.load_account()
